default_platform(:android)

platform :android do
  desc "Deploy app to firebase app distribution"
  lane :deploy do
    version = ENV['APP_VERSION'] || "1.0.0"
    sh "flutter build apk --flavor prod --build-name=#{version} --target lib/main_prod.dart"
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'], 
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      groups: "testers", 
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
      release_notes: "Automated deployment via Fastlane"
    )
  end
end
